name:                disk-load
version:             0.1.0.0
github:              "MuratOzsoyler/disk-load"
license:             BSD3
author:              "Murat Özsöyler"
maintainer:          "murat.ozsoyler@gmail.com"
copyright:           "2020 Murat Özsöyler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MuratOzsoyler/disk-load#readme>

dependencies:
- base >= 4.7 && < 5
- data-default-class
- extra
- gi-gio
- gi-glib
- gi-gtk
- reactive-banana
- reactive-banana-gi-gtk
# - gi-gtk-declarative
# - gi-gtk-declarative-app-simple
- monad-loops
- regex-applicative-text
- time
- text
- turtle
- vector

default-extensions:
  FlexibleContexts
  LambdaCase
  OverloadedLabels
  OverloadedLists
  OverloadedStrings
  RecordWildCards
  ScopedTypeVariables

library:
  source-dirs: src

executables:
  # disk-load-exe:
  #   main:                Main.hs
  #   source-dirs:         app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - disk-load
  gui-test-exe:
    main:                Main.hs
    source-dirs:         gui-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - disk-load

tests:
  disk-load-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - disk-load
